import "./components/dropdown"
import "./components/accordion"
import "./components/modal"
import "./components/mask"
import "./components/burger"
import "./components/swiper"
import "./components/review"
import "./components/contacts-form"
import "./components/registration-form"
import "./components/footer-parallax"
import "./components/move-img"
import "./components/counter"

import "./style.css"
